version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./html_testing:/var/www/html_testing
      - ./nginx/conf.d:/etc/nginx/conf.d/
    restart: unless-stopped
    ports:
      - "80:80"
    container_name: nginx_html